[project]
name = "portfolio_tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"pandas>=2.1",
	"streamlit>=1.38",
]
